### ISSUE TITLE
cant start the api

### ISSUE THREAD

**Issue by jc4balos** [Elleined/email-sender-api#2]
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 g e s ' Space ' - c p ' Space ' C : \ U s e r s \ u s e r \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 2 6 6 8 4 1 9 4 5 9 c 7 e b 6 3 7 b d 4 b 5 3 d 6 a f 1 4 3 c e \ r e d h a t . j a v a \ j d t _ w s \ j d t . l s - j a v a - p r o j e c t \ b i n ' Space ' c o m . e l l e i n e d . e m a i l s e n d e r a p i . E m a i l S e n d e r A p p l i c a t i o n ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by jc4balos** [comment]
@Elleined

**Comment by jc4balos** [comment]
remove <compilerArgs>--enable-preview</compilerArgs> from pom.xml
